export const errorAlphanumeric = 'must contains only letters and numbers';
export const errorAlpha = 'must contains only letters';
export const errorEmail = 'Incorrect email address';
export const errorNumber = 'must contains only numbers';
export const errorSignIn = 'Email or password is not correct';
export const errorSignUp = 'The email is already in use, try another email';
export const errorLength = (min, max) => `must be from ${min} to ${max} length`;
export const errorNotEmpty = (field) => `field ${field} cannot be empty`;
export const errorUUID = 'must be Mongo id';
export const errorVerify = 'Verification failed, please check your email';
export const errorJWT = 'Incorrect JWT';
